disabled_rules: # rule identifiers to exclude from running
  - class_delegate_protocol
  - cyclomatic_complexity
  - legacy_constructor
  - force_cast
  - colon
  - trailing_whitespace
  - syntactic_sugar
  - redundant_string_enum_value
  - redundant_optional_initialization
  
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  #- empty_count # Find all the available rules by running: `swiftlint rules`
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

   # Exclude files with a wildcard
  - DMY\ Capitol/DMY\ Capitol/Storyboard/Base.lproj/Main.storyboard

#force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
function_body_length:
  warning: 150
  error: 200
  
# they can set both implicitly with an array

# or they can set both explicitly
type_body_length:
  - 500 # warning
  - 600 # error
  
file_length:
  warning: 700
  error: 1200
line_length:
  warning: 240
  error: 350
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  allowed_symbols: ["_"]
  min_length: # only min_length
    error: 1 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
  allowed_symbols: ["_"]
reporter: "xcode"  # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
custom_rules:
        comma_space_rule:
                include: "*.swift"
                regex: '([}]\n[[:blank:]]*func\s\w+(\(.*\))\s[{])'
                name: "Single line space between functions"
                message: "Single line space violation: Expected single whitespace between functions"
                severity: warning
